### ISSUE TITLE
We need a logo

### ISSUE THREAD

**Issue by erciccione** [haveno-dex/haveno-meta#1]
The present logo is a stock image. We need something unique for Haveno.

**Comment by erciccione** [comment]
test comment

**Comment by erciccione** [comment]
test

**Comment by MasFlam** [comment]
Hey, I made this logo for Haveno, available as svg [here](https://masflam.com/static/haveno-logo-1.svg).
![logo](https://masflam.com/static/haveno-logo-1.png)
Let me know what you think about it and what can be improved :) (I share this under CC0)

**Comment by erciccione** [comment]
Thanks for submitting this @MasFlam!, but it's important to not include the Monero logo in our logo as it could give the feeling of being Endorsed by Monero :)

**Comment by MasFlam** [comment]
Ah, I for some reason figured the opposite. I'll remove it and add some other detail then

**Comment by MasFlam** [comment]
It still feels a bit bland, but it's better now: [png](https://masflam.com/static/haveno-logo-1.png), [svg](https://masflam.com/static/haveno-logo-1.svg)

**Comment by anhdres** [comment]
I make this proposals:

![haveno_a](https://user-images.githubusercontent.com/31753665/114177092-5f2a4980-9912-11eb-81e3-c837489aac0d.jpg)
![haveno_c](https://user-images.githubusercontent.com/31753665/114177102-63566700-9912-11eb-963f-93d1d7ad89a2.jpg)
![haveno_d](https://user-images.githubusercontent.com/31753665/114177109-65b8c100-9912-11eb-89d4-94562f08110a.jpg)


Basically I tried to make it a sibling to monero, that's why I choose an angle for the H that made it more "M" which is also a good perspective to make it shape like a harbour. I took inspiration from [old harbour markets](http://factsanddetails.com/world/cat56/sub408/entry-6382.html) and its [imagery](https://www.alamy.com/stock-photo/ancient-sea-trade.html).

There are several options to explore there and iterate. I hope it helps.

**Comment by MasFlam** [comment]
I like the first one you sent the most, way better than whatever I could come have come up with. The colors (at lest the arches) don't match the ones in monero's logo though.

**Comment by anhdres** [comment]
> The colors (at lest the arches) don't match the ones in monero's logo though.

That's intentional. They're a bit more contrasty than the originals to keep the associations but not making it look like a Monero official project. They could be even more different IMO.

A subtle nod I like is that the columns supporting the harbour have three legs shaped like an M, like Monero as a foundations of it all.

**Comment by fischdecasio** [comment]
My final design for the logo. Primarily I drew inspiration from the existing Monero logo, basing it instead of an M on an H for Haveno and trying to keep its minimalist simple style. Furthermore it represents a swap, with the left and right area symbolizing a Bitcoin and Monero block respectively, which are connected through a thicker line. Regarding the Haveno/harbor theme it could also be seen as two ship containers sitting at a dock, with the sea in the background. The colors follow the Monero pattern, with the bottom color staying the same, the left being Bitcoin's, the one on the right representing Monero's and the top one being an alteration of the complementary color to Monero's orange.[
![havenologo](https://user-images.githubusercontent.com/82228043/114249147-0acaac80-999a-11eb-982f-20ec8ed4ca03.png)
](url)

**Comment by tejstead** [comment]
@fischdecasio I really like this logo, it really integrates the Monero aesthetic while also communicating that it's a different, unaffiliated project.

**Comment by Gitdownwiththefunkysound** [comment]
@fischdecasio Excellent Logo. I need a logo for a project i'm doing. It's a website called FuZion. based on fusion the process of atoms bonding to produce energy. In this case the atoms represent the users of the website. i need something representing this fusion process with a lowercase letter f. or something with the word fuzion, and also a logo using the seperate letters in the word fuzion to represent a Breaking Bad style logo based on the periodic table of elements. If you want to fab me something up we could discuss pricing first. And i would gladly give you a deposit, thanks.

**Comment by fischdecasio** [comment]
> @fischdecasio Excellent Logo. I need a logo for a project i'm doing. It's a website called FuZion. based on fusion the process of atoms bonding to produce energy. In this case the atoms represent the users of the website. i need something representing this fusion process with a lowercase letter f. or something with the word fuzion, and also a logo using the seperate letters in the word fuzion to represent a Breaking Bad style logo based on the periodic table of elements. If you want to fab me something up we could discuss pricing first. And i would gladly give you a deposit, thanks.

I'm afraid I might not be able to do this, but I can certainly give it a try without you having to pay me anything first. You can write  me on Element, user name is the same as here.

**Comment by LukeAldevindo** [comment]
Here's a logo idea that I put together.  Feedback appreciated.
![haveno](https://user-images.githubusercontent.com/82405856/114437977-1945dd80-9bbf-11eb-9495-e59a981bb136.png)

**Comment by newspromo** [comment]
> Here's a logo idea that I put together.  The lighthouse gives the feeling of a harbor, with the orange Monero wave at the bottom to indicate that Monero is the foundation of this DEX.  Also, the stars could be thought of as decentralized nodes.
> 
> Feedback appreciated.
> 
> ![haveno](https://user-images.githubusercontent.com/82405856/114437977-1945dd80-9bbf-11eb-9495-e59a981bb136.png)
> 
> 

I like the nodes up in the sky like stars. It's clever how you thought about that. Have you tried seeing what it would look like if all the nodes had lines connecting them like in a network?

**Comment by subreme** [comment]
ErCiccione already said that he'd prefer not to use the Monero logo on the [Haveno Server](https://matrix.to/#/!cSwJDzxRuWndmFUZTd:haveno.network/$tGOUaeBlWJKQsqQ-2knPbSX5xBD4umdyB5FCJa6oCoY), but while I like the idea behind fischdecasio's logo proposal I find the "H" he used to look a little weird, so I might as well leave my [original proposal](https://matrix.to/#/!cSwJDzxRuWndmFUZTd:haveno.network/$7mbxhEW6zRVNF16S6nf1q9IXYbOEpf1Qncua3EmwNHw) here.

I'll see if I can come up with a better alternative (especially if you guys like the idea of combining the Monero orange with its complementary blue color, as fischdecasio suggested).
Maybe we could completely replace the orange with blue, spinning off the Monero logo similarly to how Bitcoin Cash modified the Bitcoin logo?

It could still be pretty cool if someone managed to design a logo containing something similar to a container ship, kind of like the [Docker logo](https://matrix.to/#/!cSwJDzxRuWndmFUZTd:haveno.network/$pNhRtWXJXiMs0g4bUHrjwh3dVRSry5PMLeEBhfXPdNE), we'll see...
![image](https://user-images.githubusercontent.com/71085002/114533633-62913e00-9c4e-11eb-892a-7b148dbe0efd.png)

**Comment by niyid** [comment]
Best design I have seen. Simple. Effective (tells a connection).

**Comment by newspromo** [comment]
For this logo, after having learned the meaning behind the name Haveno; port. I researched images of ports to draw inspiration from and found that, in a majority of the images I would see there where large crane like structures I assume to be for lifting boats and cargo. I incorporated these structures into the logo in the shape of the wedge's you see lifting what appear to be coins. I like to imagine the two cranes in the logo to be 2 peers preparing to exchange their coins in a trade and the front crane is getting its coin from out the water while the other crane waits. 

These are two versions for this logo that I’ve put together after having received some feedback in the dev chat and from looking here at all your ideas. 

A more simplified look to the left and a more artistic look to the right.

![IMG_1189](https://user-images.githubusercontent.com/75907910/114568786-7040c680-9c42-11eb-9a91-340b88bad709.PNG)

**Comment by newspromo** [comment]
Here are some closer looks at the design

With title: 

![IMG_1190](https://user-images.githubusercontent.com/75907910/114570173-9ca91280-9c43-11eb-833a-3754ca30d29c.PNG)

Simplified:

![IMG_1191](https://user-images.githubusercontent.com/75907910/114570294-b5192d00-9c43-11eb-93fa-edd859e76f83.PNG)

Artistic:

![IMG_1192](https://user-images.githubusercontent.com/75907910/114570375-c82bfd00-9c43-11eb-8fff-31edba590df0.PNG)

**Comment by anhdres** [comment]
A new idea based on the docker thing someone mentioned. I still like the "harbor"idea more, since it's the place where the trading takes place, but this container ship with negative H in there is probably clearer and works better in small sizes:

![haveno_v2_a](https://user-images.githubusercontent.com/31753665/114571666-3a550f80-9c4d-11eb-99b9-b5e0d48bbbe7.png)
![haveno_v2_b](https://user-images.githubusercontent.com/31753665/114571675-3b863c80-9c4d-11eb-9eba-0c507a7d22e5.png)
![haveno_v2_c](https://user-images.githubusercontent.com/31753665/114571678-3b863c80-9c4d-11eb-9dca-10bdeeb53f23.png)

**Comment by anhdres** [comment]
Last exploration, based on the idea of a safe haven, tax haven, whatever haven: a destination to be sheltered. So island themed, with a start marking the capital or main city, defined coastline, elevation, and adjacent waters. Extra point because the star and te top of the H make a little house negative space shape.

![haveno_v3_a](https://user-images.githubusercontent.com/31753665/114596882-86f91480-9c66-11eb-81e8-abfbe1a1e50b.png)

These would also work well in icon sizes. This next one I like better because of the stronger red color, but changed the star pointing the city for a dot because it was too _viva la revolución_

![haveno_v3_b](https://user-images.githubusercontent.com/31753665/114597122-ce7fa080-9c66-11eb-8413-de1630f9afbc.png)

and accompanying full logo:
![haveno_v3_c](https://user-images.githubusercontent.com/31753665/114597401-20c0c180-9c67-11eb-9c13-f56913fcdbe1.png)

**Comment by LukeAldevindo** [comment]
> > Here's a logo idea that I put together.  The lighthouse gives the feeling of a harbor, with the orange Monero wave at the bottom to indicate that Monero is the foundation of this DEX.  Also, the stars could be thought of as decentralized nodes.
> > Feedback appreciated.
> > ![haveno](https://user-images.githubusercontent.com/82405856/114437977-1945dd80-9bbf-11eb-9495-e59a981bb136.png)
> 
> I like the nodes up in the sky like stars. It's clever how you thought about that. Have you tried seeing what it would look like if all the nodes had lines connecting them like in a network?

I tried that but couldn't seem to get it to look quite right.  I'll give it another shot.

**Comment by newspromo** [comment]
> > > Here's a logo idea that I put together.  The lighthouse gives the feeling of a harbor, with the orange Monero wave at the bottom to indicate that Monero is the foundation of this DEX.  Also, the stars could be thought of as decentralized nodes.
> > > Feedback appreciated.
> > > ![haveno](https://user-images.githubusercontent.com/82405856/114437977-1945dd80-9bbf-11eb-9495-e59a981bb136.png)
> > 
> > 
> > I like the nodes up in the sky like stars. It's clever how you thought about that. Have you tried seeing what it would look like if all the nodes had lines connecting them like in a network?
> 
> I tried that but couldn't seem to get it to look quite right. I'll give it another shot.

Yea I tried something similar with mines but it didn't look right neither.

**Comment by LukeAldevindo** [comment]
> > > I like the nodes up in the sky like stars. It's clever how you thought about that. Have you tried seeing what it would look like if all the nodes had lines connecting them like in a network?
> > 
> > 
> > I tried that but couldn't seem to get it to look quite right. I'll give it another shot.
> 
> Yea I tried something similar with mines but it didn't look right neither.

Okay, what do you think of this?  I also made the top section of the lighthouse a bit less rounded.
![haveno_b](https://user-images.githubusercontent.com/82405856/114627900-f0504600-9cad-11eb-9909-0698471d2074.png)

**Comment by newsyp** [comment]
> > > > I like the nodes up in the sky like stars. It's clever how you thought about that. Have you tried seeing what it would look like if all the nodes had lines connecting them like in a network?
> 
> > > 
> 
> > > 
> 
> > > I tried that but couldn't seem to get it to look quite right. I'll give it another shot.
> 
> > 
> 
> > Yea I tried something similar with mines but it didn't look right neither.
> 
> 
> 
> Okay, what do you think of this?  I also made the top section of the lighthouse a bit less rounded.
> 
> ![haveno_b](https://user-images.githubusercontent.com/82405856/114627900-f0504600-9cad-11eb-9909-0698471d2074.png)
> 
> 

I think you figured out a smart way to incorporate this idea using the dotted lines to connect the nodes, but looking at it and comparing the two I think the original looks best.

**Comment by erciccione** [comment]
Two nice proposals from twitter and reddit:

![EyejZV2UYAASsR-](https://user-images.githubusercontent.com/28106476/114716255-2afcc180-9d34-11eb-98f6-558027f711f3.jpg)
https://twitter.com/mydomainsapp/status/1380251703144968192

![HAVENO](https://user-images.githubusercontent.com/28106476/114716327-3e0f9180-9d34-11eb-8542-44d119552304.png)
https://www.reddit.com/r/Monero/comments/mmrchk/im_happy_to_announce_haveno_the_monero_based_dex/gtx336q/

**Comment by anhdres** [comment]
wallpaper based on the logo: 
![haveno_wallpaper](https://user-images.githubusercontent.com/31753665/114761116-79ab5b00-9d36-11eb-833b-2c8784c65a1d.jpg)

**Comment by anhdres** [comment]
Zip file with the 3 versions of the logo in SVG, PNG with alpha, and JPG

[Haveno.zip](https://github.com/haveno-dex/haveno-meta/files/6312974/Haveno.zip)

**Comment by erciccione** [comment]
This issue is resolved. I will upload logos and meeting logs on this repo.

Thanks everybody :)
